//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_RRHHEntities : DbContext
    {
        public db_RRHHEntities()
            : base("name=db_RRHHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Clientes_Telefonos> Clientes_Telefonos { get; set; }
        public virtual DbSet<Consultores> Consultores { get; set; }
        public virtual DbSet<Entrevistas> Entrevistas { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Evaluaciones> Evaluaciones { get; set; }
        public virtual DbSet<Ofertas_Laborales> Ofertas_Laborales { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Postulantes> Postulantes { get; set; }
        public virtual DbSet<Psicologos> Psicologos { get; set; }
        public virtual DbSet<Requisitos> Requisitos { get; set; }
        public virtual DbSet<Tipo_Evaluaciones> Tipo_Evaluaciones { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
    
        [DbFunction("db_RRHHEntities", "fnCliente")]
        public virtual IQueryable<fnCliente_Result> fnCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCliente_Result>("[db_RRHHEntities].[fnCliente]()");
        }
    
        [DbFunction("db_RRHHEntities", "fnOfertasLaborales")]
        public virtual IQueryable<fnOfertasLaborales_Result> fnOfertasLaborales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOfertasLaborales_Result>("[db_RRHHEntities].[fnOfertasLaborales]()");
        }
    
        [DbFunction("db_RRHHEntities", "fnPerfiles")]
        public virtual IQueryable<fnPerfiles_Result> fnPerfiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPerfiles_Result>("[db_RRHHEntities].[fnPerfiles]()");
        }
    
        [DbFunction("db_RRHHEntities", "fnPostulantes")]
        public virtual IQueryable<fnPostulantes_Result> fnPostulantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPostulantes_Result>("[db_RRHHEntities].[fnPostulantes]()");
        }
    }
}
